-- =====================================================================
-- /free (한문장 자유공모전) Supabase 셋업
-- Supabase 대시보드 > SQL Editor 에 붙여넣고 한 번 실행하세요.
-- 폼(public/free/index.html)은 anon 키로 클라이언트에서 직접 insert/upload 합니다.
-- =====================================================================

-- 1) 제출 데이터 테이블 -------------------------------------------------
create table if not exists public."AD-ieum-free" (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  name           text,
  age            text,
  phone          text,
  email          text,
  region         text,
  address_detail text,
  job            text,
  channel        text,          -- 유입 경로
  q1             text,
  q2             text,
  q3             text,
  q4             text,
  pledge_agreed  boolean default false,
  privacy_agreed boolean default false,
  file_url       text,          -- 첨부파일 public URL (없으면 빈 문자열)
  receipt_number text
);

-- RLS: anon 키로 insert 만 허용 (조회/수정/삭제는 막아 둠) ---------------
alter table public."AD-ieum-free" enable row level security;

drop policy if exists "anon insert AD-ieum-free" on public."AD-ieum-free";
create policy "anon insert AD-ieum-free"
  on public."AD-ieum-free"
  for insert
  to anon
  with check (true);

-- 2) 첨부파일 Storage 버킷 -------------------------------------------------
-- public 버킷으로 생성 (이미 있으면 무시)
insert into storage.buckets (id, name, public)
values ('free', 'free', true)
on conflict (id) do nothing;

-- anon 업로드 허용 정책 (submissions/ 경로 한정)
drop policy if exists "anon upload free bucket" on storage.objects;
create policy "anon upload free bucket"
  on storage.objects
  for insert
  to anon
  with check (bucket_id = 'free');

-- public 읽기 허용 (버킷이 public이면 자동이지만 명시)
drop policy if exists "public read free bucket" on storage.objects;
create policy "public read free bucket"
  on storage.objects
  for select
  to public
  using (bucket_id = 'free');
